### ISSUE TITLE
Brew not supported in the Enterprise

### ISSUE THREAD

**Issue by built2order** [microsoft/homebrew-mssql-release#38]
Many Enterprise organisations are unable to support brew and making an Enterprise toolset available only on brew limits it's availability for Enterprise users. 

Please make these tools available for offline installation preferably in a .pkg format.

**Comment by v-chojas** [comment]
Since a new version was release, those links are now

https://download.microsoft.com/download/1/9/A/19AF548A-6DD3-4B48-88DC-724E9ABCEB9A/msodbcsql-17.5.1.1.tar.gz
and
https://download.microsoft.com/download/F/D/1/FD16AA69-F27D-440E-A15A-6C521A1972E6/mssql-tools-17.5.1.2.tar.gz

Anyway, closing this since it is answered.
