### ISSUE TITLE
Silent installs no longer possible

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/homebrew-mssql-release#84]
With the removal of the `HOMEBREW_NO_ENV_FILTERING` environment variable, one cannot pass the `ACCEPT_EULA` flag to the installer. There's [a PR](https://github.com/microsoft/homebrew-mssql-release/pull/26) that's 3 1/2 years (!) old to address this. Let's get it out there (perhaps with a change to the environment variable name, as indicated in the comments on the PR).

**Comment by v-chojas** [comment]
Thanks for the feedback, we will consider it.

**Comment by krymtkts** [comment]
@v-chojas
I am trying to use `echo YES | brew install msodbcsql18 mssql-tools18` instead of `HOMEBREW_NO_ENV_FILTERING ` in GitHub Actions, but it does not work.

I referred to the following.
- [Install the Microsoft ODBC driver for SQL Server (macOS) - ODBC Driver for SQL Server | Microsoft Learn](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15#microsoft-odbc-18)
- [Use HOMEBREW_ACCEPT_EULA as env variable for Homebrew 1.4+ compatibility by davidjb · Pull Request #26 · microsoft/homebrew-mssql-release](https://github.com/microsoft/homebrew-mssql-release/pull/26)

It seems that `echo YES` does not pass the license check.

![image](https://user-images.githubusercontent.com/13184040/191159158-bb997696-bf93-4388-af0c-3afafdc71853.png)

**Comment by thelazurite-cell** [comment]
As a work around for the moment I've ended up modifying the homebrew installer script so that it allows you to specify specific commits to install an older version of homebrew, and then provide a variable to stop auto updating of the tool.. I can't really say that it's really the best way to do this and it would be much better if it's fixed. 

Feel free to take a look at this to see if it helps you guys out, and modify the script as needed if it doesn't fit your needs
```/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/thelazurite-cell/install/master/install.sh)"```

In pipeline provide the following env variables 
```yaml    
    HOMEBREW_BREW_GIT_BRANCH: "c5731faf8be1ddc1eeae4b162b88bd76318fc279"
    HOMEBREW_CORE_GIT_BRANCH: "6acac26d08f5ea6b0ae33d19e862b0aec8070d6a"
    HOMEBREW_NO_AUTO_UPDATE: 1
```

Hope this helps someone else out :)

**Comment by v-chojas** [comment]
@krymtkts  does it work if you use it to install only msodbcsql18 ?

`echo YES | brew install msodbcsql18`

**Comment by krymtkts** [comment]
@v-chojas 
`echo YES | brew install msodbcsql18` doesn't work too.
[The screenshot of previous comment](https://user-images.githubusercontent.com/13184040/191159158-bb997696-bf93-4388-af0c-3afafdc71853.png) is the output of `echo YES | brew install msodbcsql18`.

**Comment by krymtkts** [comment]
I have seen the update. #85 
It works fine with GitHub Actions.
Thank you.

**Comment by Cyberbeni** [comment]
`HOMEBREW_ACCEPT_EULA=Y`
